# Generated by Django 6.1.1 on 2026-09-22 08:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(db_index=True, max_length=200)),
                ('tavsif', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Muallif',
                'verbose_name_plural': 'Mualliflar',
                'ordering': ['ism'],
            },
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi_uz', models.CharField(max_length=100)),
                ('nomi_ru', models.CharField(blank=True, max_length=100)),
                ('nomi_en', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('tartib', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Kitob turi',
                'verbose_name_plural': 'Kitob turlari',
                'ordering': ['tartib', 'nomi_uz'],
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fish', models.CharField(db_index=True, max_length=200)),
                ('guruh', models.CharField(blank=True, max_length=50)),
                ('telefon', models.CharField(blank=True, max_length=20)),
                ('izoh', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
                'ordering': ['fish'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(db_index=True, max_length=300)),
                ('slug', models.SlugField(blank=True, max_length=300, unique=True)),
                ('tavsif', models.TextField(blank=True)),
                ('nashriyot', models.CharField(blank=True, max_length=200)),
                ('yil', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('til', models.CharField(choices=[('uz', "O'zbekcha"), ('ru', 'Русский'), ('en', 'English')], default='uz', max_length=5)),
                ('muqova_key', models.CharField(blank=True, max_length=500)),
                ('korishlar_soni', models.PositiveIntegerField(default=0)),
                ('qoshilgan_sana', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('mualliflar', models.ManyToManyField(blank=True, related_name='kitoblar', to='catalog.author')),
                ('turi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kitoblar', to='catalog.form')),
            ],
            options={
                'verbose_name': 'Kitob',
                'verbose_name_plural': 'Kitoblar',
                'ordering': ['-qoshilgan_sana'],
            },
        ),
        migrations.CreateModel(
            name='BookFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_key', models.CharField(max_length=500)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB')], max_length=10)),
                ('hajm', models.PositiveBigIntegerField(default=0)),
                ('sahifalar_soni', models.PositiveIntegerField(blank=True, null=True)),
                ('tartib', models.PositiveSmallIntegerField(default=0)),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fayllar', to='catalog.book')),
            ],
            options={
                'verbose_name': 'Kitob fayli',
                'verbose_name_plural': 'Kitob fayllari',
                'ordering': ['tartib', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LoanEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('berilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('qaytarilgan_sana', models.DateTimeField(blank=True, null=True)),
                ('izoh', models.TextField(blank=True)),
                ('kitob', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qarzlar', to='catalog.book')),
                ('kutubxonachi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='berilgan_qarzlar', to=settings.AUTH_USER_MODEL)),
                ('oquvchi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='qarzlar', to='catalog.reader')),
            ],
            options={
                'verbose_name': 'Jurnal yozuvi',
                'verbose_name_plural': 'Jurnal yozuvlari',
                'ordering': ['-berilgan_sana'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi_uz', models.CharField(max_length=100)),
                ('nomi_ru', models.CharField(blank=True, max_length=100)),
                ('nomi_en', models.CharField(blank=True, max_length=100)),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True)),
                ('tartib', models.PositiveSmallIntegerField(default=0)),
                ('ota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bolalar', to='catalog.subject')),
            ],
            options={
                'verbose_name': "Yo'nalish",
                'verbose_name_plural': "Yo'nalishlar",
                'ordering': ['tartib', 'nomi_uz'],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='yonalishlar',
            field=models.ManyToManyField(blank=True, related_name='kitoblar', to='catalog.subject'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['turi', 'til'], name='catalog_boo_turi_id_42de7c_idx'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-qoshilgan_sana'], name='catalog_boo_qoshilg_5411c6_idx'),
        ),
    ]
