# Generated by Django 6.1.1 on 2026-09-22 09:23

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiBotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(default='Kutubxona AI Maslahatchisi', max_length=100)),
                ('tizim_prompti', models.TextField(default="Siz maktab va kollej elektron kutubxonasining aqlli virtual maslahatchisisiz. Vazifangiz: o'quvchilarga kerakli kitoblarni topishda yordam berish, darsliklar va ilmiy mavzular bo'yicha tushunarli maslahatlar berish. Har doim o'zbek tilida (yoki foydalanuvchi murojaat qilgan tilda) xushmuomala, aniq va dalillarga asoslangan javob bering.", help_text="AI uchun tizim yo'riqnomasi (System Prompt). Admin buni xohlagan vaqt o'zgartirishi mumkin.")),
                ('model_nomi', models.CharField(default='deepseek-chat', max_length=50)),
                ('harorat', models.FloatField(default=0.7, help_text="Ijodiylik darajasi (0.0 — qat'iy/aniq, 1.0 — ijodiy). Standart: 0.7")),
                ('max_tokens', models.PositiveIntegerField(default=2000, help_text='Javob uchun maksimal tokenlar soni')),
                ('katalog_konteksti_yoqilgan', models.BooleanField(default=True, help_text="Kutubxonada mavjud kitoblar ro'yxatini AI tizimiga avtomatik kontekst sifatida uzatish")),
                ('faol', models.BooleanField(default=True, help_text='Ushbu konfiguratsiya faolmi?')),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_sana', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Bot Sozlamasi',
                'verbose_name_plural': 'AI Bot Sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('yangilangan_sana', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'AI Suhbat Sessiyasi',
                'verbose_name_plural': 'AI Suhbat Sessiyalari',
                'ordering': ['-yangilangan_sana'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'AI Maslahatchi'), ('system', 'Tizim')], max_length=20)),
                ('matn', models.TextField()),
                ('yaratilgan_sana', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xabarlar', to='catalog.chatsession')),
            ],
            options={
                'verbose_name': 'Suhbat xabari',
                'verbose_name_plural': 'Suhbat xabarlari',
                'ordering': ['yaratilgan_sana'],
            },
        ),
    ]
