# Generated by Django 6.1.1 on 2026-09-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_aibotconfig_tizim_prompti'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='mavjudlik',
            field=models.CharField(choices=[('raqamli', "Raqamli — onlayn o'qish mumkin"), ('bosma', 'Faqat bosma nusxa — kutubxonadan olinadi')], db_index=True, default='raqamli', help_text="Raqamli — PDF/EPUB yuklang, saytda o'qiladi. Faqat bosma — faqat muqova yuklang, saytda «kutubxonadan olasiz» deb ko'rinadi.", max_length=10),
        ),
    ]
