# Generated by Django 6.1.1 on 2026-09-23 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_book_mavjudlik'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanentry',
            options={'ordering': ['-berilgan_sana'], 'verbose_name': 'Kitob berish/qaytarish', 'verbose_name_plural': 'Kitob berish/qaytarish'},
        ),
    ]
