# Generated by Django 6.1.1 on 2026-09-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_rename_loanentry_admin_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='nusxalar_soni',
            field=models.PositiveIntegerField(blank=True, help_text='Bosma kitob uchun kutubxonadagi nusxalar soni.', null=True, verbose_name='Nusxalar soni'),
        ),
    ]
