# Generated by Django 6.1.1 on 2026-09-25 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_book_nusxalar_soni'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalBook',
            fields=[
            ],
            options={
                'verbose_name': 'Raqamli kitob',
                'verbose_name_plural': 'Raqamli kitoblar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.book',),
        ),
        migrations.CreateModel(
            name='PrintedBook',
            fields=[
            ],
            options={
                'verbose_name': 'Bosma kitob',
                'verbose_name_plural': 'Bosma kitoblar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.book',),
        ),
    ]
