# Generated by Django 6.1.1 on 2026-09-25 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_digitalbook_printedbook'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='korishlar_soni',
            field=models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
        migrations.AlterField(
            model_name='book',
            name='mualliflar',
            field=models.ManyToManyField(blank=True, help_text='Kitob mualliflari', related_name='kitoblar', to='catalog.author', verbose_name='Mualliflar'),
        ),
        migrations.AlterField(
            model_name='book',
            name='qoshilgan_sana',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Qo'shilgan sana"),
        ),
        migrations.AlterField(
            model_name='book',
            name='turi',
            field=models.ForeignKey(help_text='Kitob turi (darslik, monografiya, badiiy adabiyot va h.k.)', on_delete=django.db.models.deletion.PROTECT, related_name='kitoblar', to='catalog.form', verbose_name='Kitob turi'),
        ),
        migrations.AlterField(
            model_name='book',
            name='yonalishlar',
            field=models.ManyToManyField(blank=True, help_text="Tegishli fan yoki soha yo'nalishlari", related_name='kitoblar', to='catalog.subject', verbose_name="Yo'nalishlar"),
        ),
        migrations.AlterField(
            model_name='bookfile',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('epub', 'EPUB')], max_length=10, verbose_name='Fayl formati'),
        ),
        migrations.AlterField(
            model_name='bookfile',
            name='hajm',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Fayl hajmi (baytlarda)'),
        ),
        migrations.AlterField(
            model_name='bookfile',
            name='kitob',
            field=models.ForeignKey(help_text="Fayl tegishli bo'lgan kitob", on_delete=django.db.models.deletion.CASCADE, related_name='fayllar', to='catalog.book', verbose_name='Kitob'),
        ),
        migrations.AlterField(
            model_name='bookfile',
            name='sahifalar_soni',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sahifalar soni'),
        ),
        migrations.AlterField(
            model_name='bookfile',
            name='storage_key',
            field=models.CharField(max_length=500, verbose_name='Storage kaliti'),
        ),
        migrations.AlterField(
            model_name='bookfile',
            name='tartib',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Tartib raqami'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='matn',
            field=models.TextField(verbose_name='Xabar matni'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='rol',
            field=models.CharField(choices=[('user', 'Foydalanuvchi'), ('assistant', 'AI Maslahatchi'), ('system', 'Tizim')], max_length=20, verbose_name='Xabar muallifi'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='session',
            field=models.ForeignKey(help_text="Xabar tegishli bo'lgan AI sessiyasi", on_delete=django.db.models.deletion.CASCADE, related_name='xabarlar', to='catalog.chatsession', verbose_name='Suhbat sessiyasi'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='yaratilgan_sana',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Yaratilgan sana'),
        ),
        migrations.AlterField(
            model_name='loanentry',
            name='berilgan_sana',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Berilgan sana'),
        ),
        migrations.AlterField(
            model_name='loanentry',
            name='izoh',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='loanentry',
            name='kitob',
            field=models.ForeignKey(help_text='Berilgan bosma kitob', on_delete=django.db.models.deletion.PROTECT, related_name='qarzlar', to='catalog.book', verbose_name='Kitob'),
        ),
        migrations.AlterField(
            model_name='loanentry',
            name='kutubxonachi',
            field=models.ForeignKey(help_text='Kitobni bergan xodim', on_delete=django.db.models.deletion.PROTECT, related_name='berilgan_qarzlar', to=settings.AUTH_USER_MODEL, verbose_name='Kutubxonachi'),
        ),
        migrations.AlterField(
            model_name='loanentry',
            name='oquvchi',
            field=models.ForeignKey(help_text="Kitob berilgan o'quvchi", on_delete=django.db.models.deletion.PROTECT, related_name='qarzlar', to='catalog.reader', verbose_name="O'quvchi"),
        ),
        migrations.AlterField(
            model_name='loanentry',
            name='qaytarilgan_sana',
            field=models.DateTimeField(blank=True, db_index=True, help_text="Kitob qaytarilganda sana yoziladi. Bo'sh bo'lsa — kitob qarzda hisoblanadi.", null=True, verbose_name='Qaytarilgan sana'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='fish',
            field=models.CharField(db_index=True, max_length=200, verbose_name='F.I.SH.'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='guruh',
            field=models.CharField(blank=True, max_length=50, verbose_name='Guruhi'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='izoh',
            field=models.TextField(blank=True, verbose_name='Izoh'),
        ),
        migrations.AlterField(
            model_name='reader',
            name='telefon',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='ota',
            field=models.ForeignKey(blank=True, help_text="Ierarxik tuzilma uchun asosiy yo'nalishni tanlang.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bolalar', to='catalog.subject', verbose_name="Yuqori yo'nalish"),
        ),
        migrations.AddIndex(
            model_name='loanentry',
            index=models.Index(fields=['kitob', 'qaytarilgan_sana'], name='catalog_loa_kitob_i_21cf66_idx'),
        ),
        migrations.AddIndex(
            model_name='loanentry',
            index=models.Index(fields=['oquvchi', 'qaytarilgan_sana'], name='catalog_loa_oquvchi_8f674f_idx'),
        ),
    ]
